import React, { useState } from 'react';
import { Habit, HabitLogs, MonthlyReport, UserProfile } from '../types';
import { generateMonthlyReport, formatDateKey } from '../utils/date';
import { downloadFile } from '../utils/storage';
import { NeumorphicCard } from './NeumorphicCard';
import { NeumorphicButton } from './NeumorphicButton';
import {
  ChevronLeft,
  ChevronRight,
  Printer,
  Copy,
  Download,
  Calendar,
  Award,
  Flame,
  CheckCircle2,
  TrendingUp,
  Sparkles,
  FileCode,
  FileText,
} from 'lucide-react';

interface MonthlyReportProps {
  habits: Habit[];
  logs: HabitLogs;
  currentUser?: UserProfile | null;
}

export const MonthlyReportView: React.FC<MonthlyReportProps> = ({
  habits,
  logs,
  currentUser,
}) => {
  const today = new Date();
  const [selectedYear, setSelectedYear] = useState(today.getFullYear());
  const [selectedMonth, setSelectedMonth] = useState(today.getMonth());
  const [inspectedDay, setInspectedDay] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);
  const [printStatus, setPrintStatus] = useState<string | null>(null);

  const report = generateMonthlyReport(habits, logs, selectedYear, selectedMonth);

  const handlePrevMonth = () => {
    if (selectedMonth === 0) {
      setSelectedMonth(11);
      setSelectedYear(y => y - 1);
    } else {
      setSelectedMonth(m => m - 1);
    }
    setInspectedDay(null);
  };

  const handleNextMonth = () => {
    if (selectedMonth === 11) {
      setSelectedMonth(0);
      setSelectedYear(y => y + 1);
    } else {
      setSelectedMonth(m => m + 1);
    }
    setInspectedDay(null);
  };

  // Real Print trigger
  const handlePrint = () => {
    try {
      window.print();
      setPrintStatus('Print dialog opened.');
      setTimeout(() => setPrintStatus(null), 3000);
    } catch (e) {
      console.error('Print failed', e);
      // Fallback: download printable HTML
      handleDownloadHtmlReport();
    }
  };

  // Generate clean standalone HTML report for print / PDF saving
  const handleDownloadHtmlReport = () => {
    const html = generatePrintableHtml(report, currentUser?.name);
    const filename = `habit-report-${report.year}-${String(report.month + 1).padStart(2, '0')}.html`;
    downloadFile(filename, html, 'text/html');
    setPrintStatus(`Downloaded printable HTML report: ${filename}`);
    setTimeout(() => setPrintStatus(null), 3500);
  };

  const generateMarkdownSummary = () => {
    let md = `# Habit Tracker — Monthly Report: ${report.monthName} ${report.year}\n\n`;
    if (currentUser?.name) {
      md += `*Tracked for: ${currentUser.name} (${currentUser.email})*\n\n`;
    }
    md += `## Executive Summary\n`;
    md += `- **Overall Completion Rate**: ${report.completionRate}%\n`;
    md += `- **Total Check-ins**: ${report.totalCompleted} / ${report.totalScheduled}\n`;
    md += `- **Perfect (100%) Days**: ${report.perfectDaysCount}\n`;
    md += `- **Top Performing Habit**: ${report.bestPerformingHabit || 'None'}\n`;
    md += `- **Longest Streak in Month**: ${report.longestStreakOverall} days\n\n`;

    md += `## Habit Performance Breakdown\n\n`;
    md += `| Habit | Category | Completed / Scheduled | Rate (%) | Longest Streak |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;
    report.habitStats.forEach(h => {
      md += `| ${h.habit.name} | ${h.habit.category} | ${h.completedDays} / ${h.scheduledDays} | ${h.percentage}% | ${h.longestStreakInMonth} days |\n`;
    });

    md += `\n*Generated by Neumorphic Habit Tracker on ${new Date().toLocaleDateString()}*\n`;
    return md;
  };

  const handleCopySummary = async () => {
    const text = generateMarkdownSummary();
    try {
      await navigator.clipboard.writeText(text);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (_) {}
  };

  const handleDownloadSummary = () => {
    const text = generateMarkdownSummary();
    const filename = `habit-report-${report.year}-${String(report.month + 1).padStart(2, '0')}.md`;
    downloadFile(filename, text, 'text/markdown');
  };

  // Find inspected day data if selected
  const inspectedDayData = inspectedDay
    ? report.calendarDays.find(d => d.dateStr === inspectedDay)
    : null;

  // Leading empty slots for calendar grid
  const firstDayOfWeek = new Date(selectedYear, selectedMonth, 1).getDay();
  const leadingBlanks = Array.from({ length: firstDayOfWeek });

  return (
    <div className="space-y-6 max-w-2xl mx-auto pb-16">
      {/* ========================================================================= */}
      {/* SCREEN VIEW (Interactive)                                                 */}
      {/* ========================================================================= */}

      {/* Month Navigator & Export Bar */}
      <NeumorphicCard className="p-4 no-print">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center space-x-2">
            <NeumorphicButton
              size="icon"
              onClick={handlePrevMonth}
              aria-label="Previous month"
            >
              <ChevronLeft className="w-5 h-5" />
            </NeumorphicButton>

            <h2 className="text-xl font-extrabold tracking-tight min-w-[170px] text-center">
              {report.monthName} {report.year}
            </h2>

            <NeumorphicButton
              size="icon"
              onClick={handleNextMonth}
              aria-label="Next month"
            >
              <ChevronRight className="w-5 h-5" />
            </NeumorphicButton>
          </div>

          {/* Action buttons */}
          <div className="flex flex-wrap items-center gap-2 self-end sm:self-auto">
            <NeumorphicButton
              size="sm"
              onClick={handleCopySummary}
              title="Copy markdown text summary"
            >
              <Copy className="w-3.5 h-3.5 mr-1" />
              <span>{copySuccess ? 'Copied!' : 'Copy'}</span>
            </NeumorphicButton>

            <NeumorphicButton
              size="sm"
              onClick={handleDownloadSummary}
              title="Download Markdown file"
            >
              <FileCode className="w-3.5 h-3.5 mr-1" />
              <span>.md</span>
            </NeumorphicButton>

            <NeumorphicButton
              size="sm"
              onClick={handleDownloadHtmlReport}
              title="Download Printable Standalone HTML"
            >
              <FileText className="w-3.5 h-3.5 mr-1 text-emerald-500" />
              <span>.html</span>
            </NeumorphicButton>

            <NeumorphicButton
              size="sm"
              variant="primary"
              onClick={handlePrint}
              title="Print or Save as PDF"
            >
              <Printer className="w-3.5 h-3.5 mr-1" />
              <span>Print / PDF</span>
            </NeumorphicButton>
          </div>
        </div>

        {printStatus && (
          <p className="text-[11px] text-indigo-600 dark:text-indigo-400 font-semibold mt-2.5 text-center">
            {printStatus}
          </p>
        )}
      </NeumorphicCard>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5 no-print">
        <NeumorphicCard className="p-4 text-center">
          <TrendingUp className="w-5 h-5 mx-auto text-indigo-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Completion Rate
          </span>
          <p className="text-2xl font-black text-indigo-600 dark:text-indigo-400 mt-1">
            {report.completionRate}%
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            {report.totalCompleted} / {report.totalScheduled} checks
          </span>
        </NeumorphicCard>

        <NeumorphicCard className="p-4 text-center">
          <Award className="w-5 h-5 mx-auto text-emerald-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Perfect Days
          </span>
          <p className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mt-1">
            {report.perfectDaysCount}
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            100% completion days
          </span>
        </NeumorphicCard>

        <NeumorphicCard className="p-4 text-center">
          <Flame className="w-5 h-5 mx-auto text-amber-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Longest Streak
          </span>
          <p className="text-2xl font-black text-amber-500 mt-1">
            {report.longestStreakOverall}
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            consecutive days
          </span>
        </NeumorphicCard>

        <NeumorphicCard className="p-4 text-center">
          <CheckCircle2 className="w-5 h-5 mx-auto text-purple-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Top Habit
          </span>
          <p
            className="text-base font-bold truncate mt-1.5 text-purple-600 dark:text-purple-400"
            title={report.bestPerformingHabit || 'None'}
          >
            {report.bestPerformingHabit || '—'}
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            highest consistency
          </span>
        </NeumorphicCard>
      </div>

      {/* Monthly Heatmap Calendar Matrix (Screen) */}
      <NeumorphicCard className="p-5 no-print">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-2">
            <Calendar className="w-5 h-5 text-indigo-500" />
            <h3 className="text-base font-bold">Monthly Heatmap Grid</h3>
          </div>
          {/* Legend */}
          <div className="flex items-center space-x-1.5 text-[10px] text-neu-muted dark:text-neu-darkMuted font-medium">
            <span>Less</span>
            <div className="w-3 h-3 rounded neu-pressed-sm" />
            <div className="w-3 h-3 rounded bg-indigo-200 dark:bg-indigo-950" />
            <div className="w-3 h-3 rounded bg-indigo-400 dark:bg-indigo-700" />
            <div className="w-3 h-3 rounded bg-indigo-600 dark:bg-indigo-500" />
            <div className="w-3 h-3 rounded bg-emerald-500" />
            <span>More</span>
          </div>
        </div>

        {/* Days of week header */}
        <div className="grid grid-cols-7 gap-2 mb-2 text-center text-[11px] font-bold text-neu-muted dark:text-neu-darkMuted uppercase">
          {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
            <div key={day}>{day}</div>
          ))}
        </div>

        {/* Day cells matrix */}
        <div className="grid grid-cols-7 gap-2">
          {leadingBlanks.map((_, idx) => (
            <div key={`blank-${idx}`} className="aspect-square opacity-0 pointer-events-none" />
          ))}

          {report.calendarDays.map(day => {
            const isToday = day.dateStr === formatDateKey(today);
            const isSelected = day.dateStr === inspectedDay;

            // Intensity background classes
            const intensityBg =
              day.intensity === 0
                ? 'neu-pressed-sm text-neu-muted dark:text-neu-darkMuted'
                : day.intensity === 1
                ? 'bg-indigo-200/80 dark:bg-indigo-950/80 text-indigo-800 dark:text-indigo-200 font-bold'
                : day.intensity === 2
                ? 'bg-indigo-400/90 dark:bg-indigo-800/90 text-white font-bold'
                : day.intensity === 3
                ? 'bg-indigo-600 dark:bg-indigo-600 text-white font-bold shadow-md'
                : 'bg-emerald-500 text-white font-black shadow-lg';

            return (
              <button
                key={day.dateStr}
                type="button"
                onClick={() => setInspectedDay(isSelected ? null : day.dateStr)}
                className={`aspect-square rounded-xl flex flex-col items-center justify-center p-1 relative transition-all text-xs ${intensityBg} ${
                  isSelected ? 'ring-2 ring-indigo-500 ring-offset-2 scale-105 z-10' : ''
                } ${isToday ? 'border-2 border-indigo-500' : ''}`}
                title={`${day.dateStr}: ${day.completedCount}/${day.scheduledCount} completed (${day.percentage}%)`}
              >
                <span className="text-xs">{day.dayOfMonth}</span>
                {day.scheduledCount > 0 && (
                  <span className="text-[9px] opacity-80 leading-none mt-0.5">
                    {day.completedCount}/{day.scheduledCount}
                  </span>
                )}
              </button>
            );
          })}
        </div>
      </NeumorphicCard>

      {/* Day Inspector Drawer (Screen) */}
      {inspectedDayData && (
        <NeumorphicCard className="p-4 neu-pressed animate-fade-in no-print">
          <div className="flex items-center justify-between mb-3 border-b border-gray-200/30 dark:border-gray-700/30 pb-2">
            <div>
              <h4 className="text-sm font-bold">
                Inspecting: {new Date(inspectedDayData.dateStr + 'T00:00:00').toLocaleDateString(undefined, {
                  weekday: 'short',
                  month: 'short',
                  day: 'numeric',
                  year: 'numeric',
                })}
              </h4>
              <p className="text-[11px] text-neu-muted dark:text-neu-darkMuted">
                {inspectedDayData.completedCount} of {inspectedDayData.scheduledCount} scheduled habits finished ({inspectedDayData.percentage}%)
              </p>
            </div>
            <NeumorphicButton size="sm" onClick={() => setInspectedDay(null)}>
              Close
            </NeumorphicButton>
          </div>

          <div className="space-y-2">
            {habits.map(habit => {
              const habitLog = logs[habit.id]?.[inspectedDayData.dateStr];
              const isCompleted = habitLog?.completed;
              return (
                <div
                  key={habit.id}
                  className="flex items-center justify-between p-2 rounded-xl neu-flat-sm text-xs"
                >
                  <div className="flex items-center space-x-2">
                    <div
                      className="w-2.5 h-2.5 rounded-full"
                      style={{ backgroundColor: habit.color }}
                    />
                    <span className="font-semibold">{habit.name}</span>
                  </div>
                  <span
                    className={`font-bold ${
                      isCompleted ? 'text-emerald-500' : 'text-gray-400'
                    }`}
                  >
                    {isCompleted ? '✓ Completed' : '— Pending'}
                  </span>
                </div>
              );
            })}
          </div>
        </NeumorphicCard>
      )}

      {/* Habit Breakdown (Screen) */}
      <NeumorphicCard className="p-5 no-print">
        <h3 className="text-base font-bold mb-4 flex items-center space-x-2">
          <Sparkles className="w-5 h-5 text-indigo-500" />
          <span>Habit Performance Breakdown</span>
        </h3>

        {report.habitStats.length === 0 ? (
          <p className="text-xs text-neu-muted dark:text-neu-darkMuted text-center py-6">
            No habits active during this month.
          </p>
        ) : (
          <div className="space-y-4">
            {report.habitStats.map(stat => (
              <div
                key={stat.habit.id}
                className="p-3.5 rounded-2xl neu-flat-sm space-y-2"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2.5">
                    <div
                      className="w-3 h-3 rounded-full"
                      style={{ backgroundColor: stat.habit.color }}
                    />
                    <div>
                      <h4 className="text-sm font-bold">{stat.habit.name}</h4>
                      <p className="text-[11px] text-neu-muted dark:text-neu-darkMuted capitalize">
                        {stat.habit.category} • {stat.habit.frequency}
                      </p>
                    </div>
                  </div>

                  <div className="text-right">
                    <span className="text-base font-extrabold text-indigo-600 dark:text-indigo-400">
                      {stat.percentage}%
                    </span>
                    <p className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
                      {stat.completedDays} / {stat.scheduledDays} days
                    </p>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="w-full h-2 rounded-full neu-pressed-sm overflow-hidden p-0.5">
                  <div
                    className="h-full rounded-full transition-all duration-300"
                    style={{
                      width: `${stat.percentage}%`,
                      backgroundColor: stat.habit.color,
                    }}
                  />
                </div>

                <div className="flex items-center justify-between text-[11px] text-neu-muted dark:text-neu-darkMuted pt-1">
                  <span>
                    Monthly Best Streak:{' '}
                    <strong className="text-amber-500">
                      {stat.longestStreakInMonth} days
                    </strong>
                  </span>
                  <span>
                    Current Streak:{' '}
                    <strong className="text-emerald-500">
                      {stat.currentStreak} days
                    </strong>
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </NeumorphicCard>

      {/* ========================================================================= */}
      {/* DEDICATED PRINT DOCUMENT (Hidden on screen, Visible only when printing)   */}
      {/* ========================================================================= */}
      <div className="hidden print:block print-only p-4 space-y-6">
        {/* Document Header */}
        <div className="border-b-2 border-slate-900 pb-4 flex justify-between items-end">
          <div>
            <h1 className="text-2xl font-black tracking-tight text-slate-900 uppercase">
              Habit Tracker — Monthly Performance Report
            </h1>
            <p className="text-base font-bold text-indigo-700 mt-1">
              Reporting Month: {report.monthName} {report.year}
            </p>
          </div>
          <div className="text-right text-xs text-slate-600">
            {currentUser?.name && (
              <p className="font-bold text-slate-900">User: {currentUser.name}</p>
            )}
            <p>Generated: {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        {/* Executive Summary Table */}
        <div className="border border-slate-300 rounded-lg p-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700 mb-2 border-b border-slate-200 pb-1">
            Executive Summary
          </h2>
          <div className="grid grid-cols-4 gap-3 text-center">
            <div className="p-2 border border-slate-200 rounded">
              <span className="text-[10px] uppercase font-bold text-slate-500">Completion Rate</span>
              <p className="text-xl font-black text-slate-900">{report.completionRate}%</p>
              <span className="text-[10px] text-slate-500">{report.totalCompleted}/{report.totalScheduled} total</span>
            </div>
            <div className="p-2 border border-slate-200 rounded">
              <span className="text-[10px] uppercase font-bold text-slate-500">Perfect (100%) Days</span>
              <p className="text-xl font-black text-emerald-700">{report.perfectDaysCount}</p>
              <span className="text-[10px] text-slate-500">days flawless</span>
            </div>
            <div className="p-2 border border-slate-200 rounded">
              <span className="text-[10px] uppercase font-bold text-slate-500">Longest Streak</span>
              <p className="text-xl font-black text-amber-700">{report.longestStreakOverall} d</p>
              <span className="text-[10px] text-slate-500">consecutive</span>
            </div>
            <div className="p-2 border border-slate-200 rounded">
              <span className="text-[10px] uppercase font-bold text-slate-500">Top Habit</span>
              <p className="text-sm font-bold text-indigo-800 truncate mt-1">
                {report.bestPerformingHabit || '—'}
              </p>
              <span className="text-[10px] text-slate-500">most consistent</span>
            </div>
          </div>
        </div>

        {/* Printable Calendar Heatmap Table */}
        <div className="border border-slate-300 rounded-lg p-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700 mb-2 border-b border-slate-200 pb-1">
            Monthly Consistency Calendar
          </h2>
          <table className="w-full text-center border-collapse text-xs">
            <thead>
              <tr className="bg-slate-100 font-bold border-b border-slate-300">
                {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => (
                  <th key={d} className="p-1 border border-slate-300">{d}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {/* Build weeks */}
              {(() => {
                const cells = [
                  ...leadingBlanks.map(() => null),
                  ...report.calendarDays,
                ];
                const rows: (typeof report.calendarDays[0] | null)[][] = [];
                for (let i = 0; i < cells.length; i += 7) {
                  rows.push(cells.slice(i, i + 7));
                }
                return rows.map((row, rIdx) => (
                  <tr key={`row-${rIdx}`}>
                    {row.map((day, cIdx) => (
                      <td
                        key={`cell-${rIdx}-${cIdx}`}
                        className={`p-1.5 border border-slate-300 align-top ${
                          day
                            ? day.intensity === 0
                              ? 'bg-slate-50 text-slate-400'
                              : day.intensity >= 3
                              ? 'bg-indigo-100 text-slate-900 font-bold'
                              : 'bg-indigo-50 text-slate-800'
                            : 'bg-slate-100/50'
                        }`}
                        style={{ height: '48px', width: '14.28%' }}
                      >
                        {day && (
                          <div className="flex flex-col justify-between h-full">
                            <span className="font-bold">{day.dayOfMonth}</span>
                            <span className="text-[9px]">
                              {day.scheduledCount > 0 ? `${day.completedCount}/${day.scheduledCount}` : '—'}
                            </span>
                          </div>
                        )}
                      </td>
                    ))}
                  </tr>
                ));
              })()}
            </tbody>
          </table>
        </div>

        {/* Printable Habit Breakdown Table */}
        <div className="border border-slate-300 rounded-lg p-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700 mb-2 border-b border-slate-200 pb-1">
            Habit Breakdown Table
          </h2>
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-100 border-b border-slate-300 font-bold text-slate-800">
                <th className="p-2 border border-slate-300">Habit Name</th>
                <th className="p-2 border border-slate-300">Category</th>
                <th className="p-2 border border-slate-300">Frequency</th>
                <th className="p-2 border border-slate-300">Completed / Sched.</th>
                <th className="p-2 border border-slate-300">Rate (%)</th>
                <th className="p-2 border border-slate-300">Longest Streak</th>
              </tr>
            </thead>
            <tbody>
              {report.habitStats.length === 0 ? (
                <tr>
                  <td colSpan={6} className="p-4 text-center text-slate-500 italic">
                    No habits active for this period.
                  </td>
                </tr>
              ) : (
                report.habitStats.map(h => (
                  <tr key={h.habit.id} className="border-b border-slate-200">
                    <td className="p-2 border border-slate-300 font-bold">{h.habit.name}</td>
                    <td className="p-2 border border-slate-300 capitalize">{h.habit.category}</td>
                    <td className="p-2 border border-slate-300 capitalize">{h.habit.frequency}</td>
                    <td className="p-2 border border-slate-300">{h.completedDays} / {h.scheduledDays}</td>
                    <td className="p-2 border border-slate-300 font-bold">
                      {h.percentage}%
                    </td>
                    <td className="p-2 border border-slate-300">{h.longestStreakInMonth} days</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Footer */}
        <div className="pt-4 border-t border-slate-300 flex justify-between text-[10px] text-slate-500">
          <span>Neumorphic Habit Tracker • Offline & Privacy-First</span>
          <span>Verified Accurate Report</span>
        </div>
      </div>
    </div>
  );
};

/**
 * Creates a standalone, self-contained printable HTML document
 */
function generatePrintableHtml(report: MonthlyReport, userName?: string): string {
  const tableRows = report.habitStats
    .map(
      h => `
    <tr>
      <td style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold;">${h.habit.name}</td>
      <td style="padding: 8px; border: 1px solid #cbd5e1; text-transform: capitalize;">${h.habit.category}</td>
      <td style="padding: 8px; border: 1px solid #cbd5e1; text-transform: capitalize;">${h.habit.frequency}</td>
      <td style="padding: 8px; border: 1px solid #cbd5e1; text-align: center;">${h.completedDays} / ${h.scheduledDays}</td>
      <td style="padding: 8px; border: 1px solid #cbd5e1; text-align: center; font-weight: bold; color: #4338ca;">${h.percentage}%</td>
      <td style="padding: 8px; border: 1px solid #cbd5e1; text-align: center;">${h.longestStreakInMonth} days</td>
    </tr>`
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Habit Tracker Report — ${report.monthName} ${report.year}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #0f172a; line-height: 1.5; }
    h1 { margin-bottom: 4px; font-size: 24px; color: #1e1b4b; }
    .header-info { color: #64748b; font-size: 13px; margin-bottom: 24px; border-bottom: 2px solid #0f172a; padding-bottom: 12px; }
    .kpi-container { display: flex; gap: 16px; margin-bottom: 28px; }
    .kpi-box { flex: 1; border: 1px solid #cbd5e1; border-radius: 8px; padding: 14px; text-align: center; background: #f8fafc; }
    .kpi-label { font-size: 11px; text-transform: uppercase; font-weight: bold; color: #64748b; }
    .kpi-val { font-size: 24px; font-weight: 900; color: #0f172a; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 13px; }
    th { background: #f1f5f9; padding: 10px; border: 1px solid #cbd5e1; text-align: left; }
    .footer { font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; display: flex; justify-content: space-between; }
    @media print {
      body { margin: 20px; }
      button { display: none !important; }
    }
  </style>
</head>
<body>
  <h1>🫧 Habit Tracker — Monthly Performance Report</h1>
  <div class="header-info">
    <div><strong>Reporting Period:</strong> ${report.monthName} ${report.year}</div>
    ${userName ? `<div><strong>User Profile:</strong> ${userName}</div>` : ''}
    <div><strong>Generated On:</strong> ${new Date().toLocaleDateString()}</div>
  </div>

  <div class="kpi-container">
    <div class="kpi-box">
      <div class="kpi-label">Completion Rate</div>
      <div class="kpi-val">${report.completionRate}%</div>
      <div style="font-size: 11px; color: #64748b;">${report.totalCompleted} / ${report.totalScheduled} check-ins</div>
    </div>
    <div class="kpi-box">
      <div class="kpi-label">Perfect Days</div>
      <div class="kpi-val" style="color: #047857;">${report.perfectDaysCount}</div>
      <div style="font-size: 11px; color: #64748b;">100% completion</div>
    </div>
    <div class="kpi-box">
      <div class="kpi-label">Longest Streak</div>
      <div class="kpi-val" style="color: #b45309;">${report.longestStreakOverall} days</div>
      <div style="font-size: 11px; color: #64748b;">consecutive consistency</div>
    </div>
    <div class="kpi-box">
      <div class="kpi-label">Top Habit</div>
      <div class="kpi-val" style="font-size: 16px; margin-top: 8px;">${report.bestPerformingHabit || '—'}</div>
      <div style="font-size: 11px; color: #64748b;">highest rate</div>
    </div>
  </div>

  <h2 style="font-size: 16px; margin-bottom: 8px;">Habit Breakdown Table</h2>
  <table>
    <thead>
      <tr>
        <th>Habit Name</th>
        <th>Category</th>
        <th>Frequency</th>
        <th style="text-align: center;">Completed / Scheduled</th>
        <th style="text-align: center;">Rate (%)</th>
        <th style="text-align: center;">Longest Streak</th>
      </tr>
    </thead>
    <tbody>
      ${tableRows || '<tr><td colspan="6" style="padding: 16px; text-align: center; color: #94a3b8;">No habits tracked this month.</td></tr>'}
    </tbody>
  </table>

  <div style="text-align: center; margin: 24px 0;">
    <button onclick="window.print()" style="padding: 10px 20px; font-weight: bold; background: #4f46e5; color: white; border: none; border-radius: 6px; cursor: pointer;">
      Print Report or Save as PDF
    </button>
  </div>

  <div class="footer">
    <span>Neumorphic Habit Tracker • Open Source</span>
    <span>Exported from Local Storage</span>
  </div>
</body>
</html>`;
}
