import React, { useState } from 'react';
import { Habit, HabitLogs } from '../types';
import { generateMonthlyReport, formatDateKey } from '../utils/date';
import { NeumorphicCard } from './NeumorphicCard';
import { NeumorphicButton } from './NeumorphicButton';
import {
  ChevronLeft,
  ChevronRight,
  Printer,
  Copy,
  Download,
  Calendar,
  Award,
  Flame,
  CheckCircle2,
  TrendingUp,
  Sparkles,
} from 'lucide-react';

interface MonthlyReportProps {
  habits: Habit[];
  logs: HabitLogs;
}

export const MonthlyReportView: React.FC<MonthlyReportProps> = ({ habits, logs }) => {
  const today = new Date();
  const [selectedYear, setSelectedYear] = useState(today.getFullYear());
  const [selectedMonth, setSelectedMonth] = useState(today.getMonth());
  const [inspectedDay, setInspectedDay] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);

  const report = generateMonthlyReport(habits, logs, selectedYear, selectedMonth);

  const handlePrevMonth = () => {
    if (selectedMonth === 0) {
      setSelectedMonth(11);
      setSelectedYear(y => y - 1);
    } else {
      setSelectedMonth(m => m - 1);
    }
    setInspectedDay(null);
  };

  const handleNextMonth = () => {
    if (selectedMonth === 11) {
      setSelectedMonth(0);
      setSelectedYear(y => y + 1);
    } else {
      setSelectedMonth(m => m + 1);
    }
    setInspectedDay(null);
  };

  const handlePrint = () => {
    window.print();
  };

  const generateMarkdownSummary = () => {
    let md = `# Habit Tracker — Monthly Report: ${report.monthName} ${report.year}\n\n`;
    md += `## Overview\n`;
    md += `- **Overall Completion Rate**: ${report.completionRate}%\n`;
    md += `- **Total Check-ins**: ${report.totalCompleted} / ${report.totalScheduled}\n`;
    md += `- **Perfect Days**: ${report.perfectDaysCount}\n`;
    md += `- **Best Habit**: ${report.bestPerformingHabit || 'None'}\n`;
    md += `- **Longest Streak in Month**: ${report.longestStreakOverall} days\n\n`;

    md += `## Habit Breakdown\n\n`;
    md += `| Habit | Category | Completed / Scheduled | Rate (%) | Longest Streak |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;
    report.habitStats.forEach(h => {
      md += `| ${h.habit.name} | ${h.habit.category} | ${h.completedDays} / ${h.scheduledDays} | ${h.percentage}% | ${h.longestStreakInMonth} days |\n`;
    });

    md += `\n*Generated by Neumorphic Habit Tracker on ${new Date().toLocaleDateString()}*\n`;
    return md;
  };

  const handleCopySummary = async () => {
    const text = generateMarkdownSummary();
    try {
      await navigator.clipboard.writeText(text);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (_) {}
  };

  const handleDownloadSummary = () => {
    const text = generateMarkdownSummary();
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `habit-report-${report.year}-${String(report.month + 1).padStart(2, '0')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Find inspected day data if selected
  const inspectedDayData = inspectedDay
    ? report.calendarDays.find(d => d.dateStr === inspectedDay)
    : null;

  // Leading empty slots for calendar grid
  const firstDayOfWeek = new Date(selectedYear, selectedMonth, 1).getDay();
  const leadingBlanks = Array.from({ length: firstDayOfWeek });

  return (
    <div className="space-y-6 max-w-2xl mx-auto pb-16">
      {/* Month Navigator & Export Bar */}
      <NeumorphicCard className="p-4 no-print">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center space-x-2">
            <NeumorphicButton
              size="icon"
              onClick={handlePrevMonth}
              aria-label="Previous month"
            >
              <ChevronLeft className="w-5 h-5" />
            </NeumorphicButton>

            <h2 className="text-xl font-extrabold tracking-tight min-w-[170px] text-center">
              {report.monthName} {report.year}
            </h2>

            <NeumorphicButton
              size="icon"
              onClick={handleNextMonth}
              aria-label="Next month"
            >
              <ChevronRight className="w-5 h-5" />
            </NeumorphicButton>
          </div>

          <div className="flex items-center space-x-2 self-end sm:self-auto">
            <NeumorphicButton
              size="sm"
              onClick={handleCopySummary}
              title="Copy text summary"
            >
              <Copy className="w-4 h-4 mr-1.5" />
              {copySuccess ? 'Copied!' : 'Copy'}
            </NeumorphicButton>

            <NeumorphicButton
              size="sm"
              onClick={handleDownloadSummary}
              title="Download report"
            >
              <Download className="w-4 h-4 mr-1.5" />
              Export
            </NeumorphicButton>

            <NeumorphicButton
              size="sm"
              variant="primary"
              onClick={handlePrint}
              title="Print or save as PDF"
            >
              <Printer className="w-4 h-4 mr-1.5" />
              Print
            </NeumorphicButton>
          </div>
        </div>
      </NeumorphicCard>

      {/* Printable Header */}
      <div className="hidden print-only mb-6 text-center">
        <h1 className="text-2xl font-bold">Monthly Habit Report</h1>
        <p className="text-sm text-gray-500">{report.monthName} {report.year}</p>
      </div>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
        <NeumorphicCard className="p-4 text-center">
          <TrendingUp className="w-5 h-5 mx-auto text-indigo-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Completion Rate
          </span>
          <p className="text-2xl font-black text-indigo-600 dark:text-indigo-400 mt-1">
            {report.completionRate}%
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            {report.totalCompleted} / {report.totalScheduled} checks
          </span>
        </NeumorphicCard>

        <NeumorphicCard className="p-4 text-center">
          <Award className="w-5 h-5 mx-auto text-emerald-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Perfect Days
          </span>
          <p className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mt-1">
            {report.perfectDaysCount}
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            100% completion days
          </span>
        </NeumorphicCard>

        <NeumorphicCard className="p-4 text-center">
          <Flame className="w-5 h-5 mx-auto text-amber-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Longest Streak
          </span>
          <p className="text-2xl font-black text-amber-500 mt-1">
            {report.longestStreakOverall}
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            consecutive days
          </span>
        </NeumorphicCard>

        <NeumorphicCard className="p-4 text-center">
          <CheckCircle2 className="w-5 h-5 mx-auto text-purple-500 mb-1.5" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-neu-muted dark:text-neu-darkMuted">
            Top Habit
          </span>
          <p className="text-base font-bold truncate mt-1.5 text-purple-600 dark:text-purple-400" title={report.bestPerformingHabit || 'None'}>
            {report.bestPerformingHabit || '—'}
          </p>
          <span className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
            highest consistency
          </span>
        </NeumorphicCard>
      </div>

      {/* Monthly Heatmap Calendar Matrix */}
      <NeumorphicCard className="p-5">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-2">
            <Calendar className="w-5 h-5 text-indigo-500" />
            <h3 className="text-base font-bold">Monthly Heatmap Grid</h3>
          </div>
          {/* Legend */}
          <div className="flex items-center space-x-1.5 text-[10px] text-neu-muted dark:text-neu-darkMuted font-medium">
            <span>Less</span>
            <div className="w-3 h-3 rounded neu-pressed-sm" />
            <div className="w-3 h-3 rounded bg-indigo-200 dark:bg-indigo-950" />
            <div className="w-3 h-3 rounded bg-indigo-400 dark:bg-indigo-700" />
            <div className="w-3 h-3 rounded bg-indigo-600 dark:bg-indigo-500" />
            <div className="w-3 h-3 rounded bg-emerald-500" />
            <span>More</span>
          </div>
        </div>

        {/* Days of week header */}
        <div className="grid grid-cols-7 gap-2 mb-2 text-center text-[11px] font-bold text-neu-muted dark:text-neu-darkMuted uppercase">
          {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
            <div key={day}>{day}</div>
          ))}
        </div>

        {/* Calendar Day Grid */}
        <div className="grid grid-cols-7 gap-2">
          {leadingBlanks.map((_, idx) => (
            <div key={`blank-${idx}`} className="aspect-square opacity-0" />
          ))}

          {report.calendarDays.map(day => {
            const isToday = day.dateStr === formatDateKey(new Date());
            const isInspected = day.dateStr === inspectedDay;

            // Compute background shade based on intensity
            let cellColor = '';
            if (day.intensity === 4) {
              cellColor = 'bg-emerald-500 text-white shadow-sm';
            } else if (day.intensity === 3) {
              cellColor = 'bg-indigo-600 text-white shadow-sm';
            } else if (day.intensity === 2) {
              cellColor = 'bg-indigo-400/80 text-white dark:bg-indigo-700';
            } else if (day.intensity === 1) {
              cellColor = 'bg-indigo-200 dark:bg-indigo-950/70 text-indigo-900 dark:text-indigo-200';
            } else {
              cellColor = day.scheduledCount > 0 ? 'neu-pressed-sm opacity-80' : 'opacity-40';
            }

            return (
              <button
                key={day.dateStr}
                type="button"
                onClick={() => setInspectedDay(day.dateStr === inspectedDay ? null : day.dateStr)}
                className={`aspect-square rounded-2xl flex flex-col items-center justify-center text-xs font-bold transition-all relative ${
                  isInspected
                    ? 'ring-2 ring-indigo-500 ring-offset-2 scale-105 z-10'
                    : 'hover:scale-105'
                } ${cellColor}`}
                title={`${day.dateStr}: ${day.completedCount}/${day.scheduledCount} completed (${day.percentage}%)`}
              >
                <span>{day.dayOfMonth}</span>
                {day.scheduledCount > 0 && (
                  <span className="text-[9px] opacity-90 font-medium">
                    {day.completedCount}/{day.scheduledCount}
                  </span>
                )}
                {isToday && (
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-400 absolute top-1 right-1" />
                )}
              </button>
            );
          })}
        </div>

        {/* Selected Day Inspector Drawer */}
        {inspectedDayData && (
          <div className="mt-4 p-4 rounded-2xl neu-pressed-sm space-y-3 animate-fade-in text-left">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-bold">
                {new Date(inspectedDayData.dateStr).toLocaleDateString('en-US', {
                  weekday: 'long',
                  month: 'short',
                  day: 'numeric',
                })}
              </h4>
              <span className="text-xs font-bold text-indigo-500">
                {inspectedDayData.percentage}% Completed ({inspectedDayData.completedCount}/{inspectedDayData.scheduledCount})
              </span>
            </div>

            <div className="space-y-1.5">
              {habits.map(h => {
                const habitDone = logs[h.id]?.[inspectedDayData.dateStr]?.completed;
                const habitNote = logs[h.id]?.[inspectedDayData.dateStr]?.note;
                const isScheduled = h.frequency === 'daily' || !h.archived;

                if (!isScheduled) return null;

                return (
                  <div
                    key={h.id}
                    className="flex items-center justify-between text-xs py-1 border-b border-gray-200/20 dark:border-gray-700/20 last:border-0"
                  >
                    <div className="flex items-center space-x-2">
                      <div
                        className="w-2 h-2 rounded-full"
                        style={{ backgroundColor: h.color }}
                      />
                      <span>{h.name}</span>
                      {habitNote && (
                        <span className="text-gray-400 italic text-[11px]">"{habitNote}"</span>
                      )}
                    </div>
                    <span>{habitDone ? '✅ Done' : '❌ Missed'}</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </NeumorphicCard>

      {/* Habit-by-Habit Detailed Performance */}
      <NeumorphicCard className="p-5">
        <h3 className="text-base font-bold mb-4 flex items-center space-x-2">
          <Sparkles className="w-5 h-5 text-indigo-500" />
          <span>Habit Performance Breakdown</span>
        </h3>

        {report.habitStats.length === 0 ? (
          <p className="text-xs text-neu-muted dark:text-neu-darkMuted text-center py-6">
            No habits active during this month.
          </p>
        ) : (
          <div className="space-y-4">
            {report.habitStats.map(stat => (
              <div
                key={stat.habit.id}
                className="p-3.5 rounded-2xl neu-flat-sm space-y-2"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2.5">
                    <div
                      className="w-3 h-3 rounded-full"
                      style={{ backgroundColor: stat.habit.color }}
                    />
                    <div>
                      <h4 className="text-sm font-bold">{stat.habit.name}</h4>
                      <p className="text-[11px] text-neu-muted dark:text-neu-darkMuted capitalize">
                        {stat.habit.category} • {stat.habit.frequency}
                      </p>
                    </div>
                  </div>

                  <div className="text-right">
                    <span className="text-base font-extrabold text-indigo-600 dark:text-indigo-400">
                      {stat.percentage}%
                    </span>
                    <p className="text-[10px] text-neu-muted dark:text-neu-darkMuted">
                      {stat.completedDays} / {stat.scheduledDays} days
                    </p>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="w-full h-2 rounded-full neu-pressed-sm overflow-hidden p-0.5">
                  <div
                    className="h-full rounded-full transition-all duration-300"
                    style={{
                      width: `${stat.percentage}%`,
                      backgroundColor: stat.habit.color,
                    }}
                  />
                </div>

                <div className="flex items-center justify-between text-[11px] text-neu-muted dark:text-neu-darkMuted pt-1">
                  <span>
                    Monthly Best Streak:{' '}
                    <strong className="text-amber-500">
                      {stat.longestStreakInMonth} days
                    </strong>
                  </span>
                  <span>
                    Current Streak:{' '}
                    <strong className="text-emerald-500">
                      {stat.currentStreak} days
                    </strong>
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </NeumorphicCard>
    </div>
  );
};
